/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/zengg/Desktop/组件库/wx-design-docs/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-2fa6df84",
    path: "/pages/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2fa6df84").then(next)
    },
  },
  {
    path: "/pages/index.html",
    redirect: "/pages/"
  },
  {
    name: "v-57f053f3",
    path: "/pages/echarts/chart.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-57f053f3").then(next)
    },
  },
  {
    name: "v-8b638cfa",
    path: "/pages/element-ui/date-picker.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8b638cfa").then(next)
    },
  },
  {
    name: "v-510f5601",
    path: "/pages/element-ui/table.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-510f5601").then(next)
    },
  },
  {
    name: "v-662501b8",
    path: "/standard/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-662501b8").then(next)
    },
  },
  {
    path: "/standard/index.html",
    redirect: "/standard/"
  },
  {
    name: "v-0a88c668",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a88c668").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]